DELETE  http://localhost:3001/api/blogs/66a8e7136df8663ac373ebd3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImltdW5pcXVlIiwiaWQiOiI2NmE4Y2QyOGU4MTJhMmExMzJjODcyMzIiLCJpYXQiOjE3MjIzNDUyMTUsImV4cCI6MTcyMjM0ODgxNX0.XTZmE2dvWdQVhMLRjnd_SJrrqHSpGE_7EKwBgjTazh4
Content-Type: application/json

{
    "title": "ggssrtt",
    "author": "chat",
    "url": "ggssr@gg.chat",
    "likes": 4
}